name: telefon_rehberi
description: normal bir telefon rehberi
version: 4.8.9+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  contacts_service: ^0.6.1
  android_intent_plus: ^5.0.2
  permission_handler: ^10.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/ico.png 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ico.png" 
